sslp/IITG/urls.py
from django.conf.urls import url
from . import views

app_name = 'IITG'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^register/$', views.register, name='register'),
    url(r'^faculty/$', views.faculty, name='faculty'),
    url(r'^facultypage/$', views.faculty_page, name='faculty_page'),
    url(r'^dept_faculty/(?P<filter_by>[a-zA_Z]+)/(?P<dept_id>[0-9]+)$', views.dept_faculty, name='dept_faculty'),
    url(r'^login_user/$', views.login_user, name='login_user'),
    url(r'^logout_user/$', views.logout_user, name='logout_user'),
    url(r'^(?P<professor_id>[0-9]+)/$', views.prof_detail, name='prof_detail'),
    url(r'^(?P<professor_id>[0-9]+)/details$', views.prof_detail_general, name='prof_detail_general'),
    url(r'^faculty/(?P<professor_id>[0-9]+)/$', views.prof_website, name='professor_website'),
    url(r'^(?P<professor_id>[0-9]+)/courses$', views.course_detail, name='course_detail'),
    url(r'^courses/(?P<filter_by>[a-zA_Z]+)/$', views.courses, name='courses'),
    url(r'^(?P<professor_id>[0-9]+)/create_course/$', views.create_course, name='create_course'),
    url(r'^(?P<professor_id>[0-9]+)/delete_course/(?P<course_id>[0-9]+)/$', views.delete_course, name='delete_course'),
    url(r'^(?P<professor_id>[0-9]+)/education$', views.education_detail, name='education_detail'),
    url(r'^educations/(?P<filter_by>[a-zA_Z]+)/$', views.educations, name='education'),
    url(r'^(?P<professor_id>[0-9]+)/create_education/$', views.create_education, name='create_education'),
    url(r'^(?P<professor_id>[0-9]+)/delete_education/(?P<education_id>[0-9]+)/$', views.delete_education, name='delete_education'),
    url(r'^(?P<professor_id>[0-9]+)/experiences$', views.experience_detail, name='experience_detail'),
    url(r'^experiences/(?P<filter_by>[a-zA_Z]+)/$', views.experiences, name='experiences'),
    url(r'^(?P<professor_id>[0-9]+)/create_experience/$', views.create_experience, name='create_experience'),
    url(r'^(?P<professor_id>[0-9]+)/delete_experience/(?P<experience_id>[0-9]+)/$', views.delete_experience, name='delete_experience'),
    url(r'^(?P<professor_id>[0-9]+)/projects$', views.project_detail, name='project_detail'),
    url(r'^projects/(?P<filter_by>[a-zA_Z]+)/$', views.projects, name='projects'),
    url(r'^(?P<professor_id>[0-9]+)/create_project/$', views.create_project, name='create_project'),
    url(r'^(?P<professor_id>[0-9]+)/delete_project/(?P<project_id>[0-9]+)/$', views.delete_project, name='delete_project'),
    url(r'^(?P<professor_id>[0-9]+)/publications$', views.publication_detail, name='publication_detail'),
    url(r'^publications/(?P<filter_by>[a-zA_Z]+)/$', views.publications, name='publications'),
    url(r'^(?P<professor_id>[0-9]+)/create_publication/$', views.create_publication, name='create_publication'),
    url(r'^(?P<professor_id>[0-9]+)/delete_publication/(?P<publication_id>[0-9]+)/$', views.delete_publication, name='delete_publication'),
    url(r'^(?P<professor_id>[0-9]+)/recognitions$', views.recognition_detail, name='recognition_detail'),
    url(r'^recognitions/(?P<filter_by>[a-zA_Z]+)/$', views.recognitions, name='recognitions'),
    url(r'^(?P<professor_id>[0-9]+)/create_recognition/$', views.create_recognition, name='create_recognition'),
    url(r'^(?P<professor_id>[0-9]+)/delete_recognition/(?P<recognition_id>[0-9]+)/$', views.delete_recognition, name='delete_recognition'),
    url(r'^(?P<professor_id>[0-9]+)/students$', views.student_detail, name='student_detail'),
    url(r'^students/(?P<filter_by>[a-zA_Z]+)/$', views.students, name='students'),
    url(r'^(?P<professor_id>[0-9]+)/create_student/$', views.create_student, name='create_student'),
    url(r'^(?P<professor_id>[0-9]+)/delete_student/(?P<student_id>[0-9]+)/$', views.delete_student, name='delete_student'),
    url(r'^create_professor/$', views.create_professor, name='create_professor'),
    url(r'^(?P<professor_id>[0-9]+)/delete_professor/$', views.delete_professor, name='delete_professor'),
    url(r'prof/update/(?P<pk>[0-9]+)/$', views.ProfUpdate.as_view(), name='prof_update'),                     #
]

sslp/sslp_new/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^IITG/', include('IITG.urls')),
    url(r'^', include('IITG.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sslp/IITG/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator, ValidationError
from django.core.urlresolvers import reverse
from django.contrib.auth.models import Permission, User
# from datetime import datetime


"""class UserProfile(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    mail = models.EmailField(max_length=150)
    password = models.CharField(max_length=50, default='IITG')  #
    Pro_pic = models.ImageField(upload_to="", default='/pro_pic.png')

#    @property
    def __str__(self):
        return self.first_name + ' ' + self.last_name
"""


class Dept(models.Model):
    Dept_name = models.CharField(max_length=100)
    Dept_detail = models.TextField

    def __str__(self):
        return self.Dept_name


class Desgn(models.Model):
    position = models.CharField(max_length=100)

    def __str__(self):
        return self.position


class Professor(models.Model):
    user = models.ForeignKey(User, default=1)
    pro_pic = models.ImageField(upload_to="", default='/pro_pic.png')
    Department = models.ForeignKey(Dept, on_delete=models.CASCADE)
    designation = models.ForeignKey(Desgn, on_delete=models.CASCADE)
    phone_no = models.IntegerField(validators=[MaxValueValidator(9999999999), MinValueValidator(1000000000)])
    room_no = models.CharField(max_length=10)
    visit_time = models.TimeField()
    Research_Interests = models.TextField(max_length=1000, default='')
    Biography = models.TextField(default='')

    def get_absolute_url(self):                                                 ###
        return reverse('IITG:prof_detail', kwargs={'pk': self.pk})          ###

    def clean_fields(self, exclude=None):
        if self.phone_no < 1000000000:
            raise ValidationError({'phone_no': [" must be a 10-digit number"]})
        if 9999999999 < self.phone_no:
            raise ValidationError({'phone_no': [" must be a 10-digit number"]})

    def __str__(self):
        return self.user.__str__()


class Course(models.Model):
    prof = models.ForeignKey(Professor, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    Dept = models.ForeignKey(Dept, on_delete=models.CASCADE)
    no = models.CharField(max_length=8)
    # credits = models.IntegerField
    # start_year = models.IntegerField
    # end_year = models.IntegerField

#    def get_absolute_url(self):
#        return reverse('IITG:prof_detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.no


class Education(models.Model):
    prof = models.ForeignKey(Professor, on_delete=models.CASCADE)
    degree = models.CharField(max_length=8)
    field = models.CharField(max_length=100)
    University = models.CharField(max_length=100)
    Year = models.CharField(max_length=6)

#    def get_absolute_url(self):
#        return reverse('IITG:prof_detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.degree


class Experience(models.Model):

    Professor = models.ForeignKey(Professor, on_delete=models.CASCADE)
    # Title = models.CharField(max_length=150)
    Detail = models.TextField()
    Institution = models.CharField(max_length=100)
    start_Year = models.CharField(max_length=10)
    end_Year = models.CharField(max_length=10)

#    def get_absolute_url(self):
#        return reverse('IITG:prof_detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.start_Year


class Recognition(models.Model):
    Professor = models.ForeignKey(Professor, on_delete=models.CASCADE)
    Name = models.CharField(max_length=100)
    Detail = models.TextField()
    Year = models.IntegerField

#    def get_absolute_url(self):
#        return reverse('project:prof_detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.Name


class Publication(models.Model):
    Professor = models.ForeignKey(Professor, on_delete=models.CASCADE)
    Name = models.CharField(max_length=150)
    Detail = models.TextField()
    Date = models.DateField()

#    def get_absolute_url(self):
#        return reverse('IITG:prof_detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.Name


class Projects(models.Model):
    Professor = models.ForeignKey(Professor, on_delete=models.CASCADE)
    Title = models.CharField(max_length=100)
    Detail = models.TextField()
    start_Year = models.CharField(max_length=10)
    end_Year = models.CharField(max_length=10)
    # start_year = models.DateField()
    # end_year = models.DateField()

#    def get_absolute_url(self):
#        return reverse('IITG:prof_detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.Title


class Student(models.Model):
    Professor = models.ForeignKey(Professor, on_delete=models.CASCADE)
    Name = models.CharField(max_length=100)
    degree = models.CharField(max_length=8)
    Detail = models.TextField()

#    def get_absolute_url(self):
#        return reverse('IITG:prof_detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.Name

sslp/IITG/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Professor, Course, Education, Experience, Projects, Publication, Recognition, Student

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'email', 'password']


class ProfessorForm(forms.ModelForm):

    class Meta:
        model = Professor
#        fields = ['course', 'album_title', 'genre', 'album_logo']
        fields = ['Department', 'designation', 'pro_pic', 'phone_no', 'room_no', 'visit_time', 'Research_Interests', 'Biography']


class CourseForm(forms.ModelForm):

    class Meta:
        model = Course
        fields = ['name', 'Dept', 'no', 'prof']
        # fields = ['name', 'Dept', 'no', 'credits', 'start_year', 'end_year', 'prof']


class EducationForm(forms.ModelForm):

    class Meta:
        model = Education
        fields = ['degree', 'field', 'University', 'Year', 'prof']


class ExperienceForm(forms.ModelForm):

    class Meta:
        model = Experience
        fields = ['Detail', 'Institution', 'start_Year', 'end_Year', 'Professor']


class ProjectsForm(forms.ModelForm):

    class Meta:
        model = Projects
        fields = ['Title', 'Detail', 'start_Year', 'end_Year', 'Professor']


class PublicationForm(forms.ModelForm):

    class Meta:
        model = Publication
        fields = ['Name', 'Detail', 'Date', 'Professor']


class RecognitionForm(forms.ModelForm):

    class Meta:
        model = Recognition
        fields = ['Name', 'Detail', 'Professor']


class StudentForm(forms.ModelForm):

    class Meta:
        model = Student
        fields = ['Name', 'degree', 'Detail', 'Professor']

sslp/IITG/templates/IITG/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Indian Institute of Technology Guwahati{% endblock %}</title>
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'IITG/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

    <script src="{% static 'IITG/js/main.js' %}"></script>
</head>
<body>

<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'IITG:index' %}">INDIAN INSTITUTE OF TECHNOLOGY GUWAHATI</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
            </ul>
            <!--
            <form class="navbar-form navbar-left" role="search" method="get" action="{% url 'IITG:index' %}">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="{{ request.GET.q }}">
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>
            -->
            <ul class="nav navbar-nav navbar-right">
                <li class="{% block professors_active %}{% endblock %}"><a href="{% url 'IITG:index' %}"> {{ user }}</a></li>
                <li>
                    <a href="{% url 'IITG:logout_user' %}">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                    </a>
                </li>
            </ul>
        </div>

    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

sslp/IITG/templates/IITG/detail_template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

sslp/IITG/templates/IITG/index.html
{% extends 'IITG/base.html' %}
{% block professors_active %}active{% endblock %}

{% block body %}
<div class="professors-container container-fluid">

    <!-- professors -->
    <div class="row">
        <div class="col-sm-12">
            <h3>{{ user.username }}</h3>
        </div>
        {% if professors %}
            {% for professor in professors %}
                <div class="col-sm-4 col-lg-2">
                    <div class="thumbnail">
                        <a href="{% url 'IITG:prof_detail' professor.id %}">
                            <img src="{{ professor.pro_pic.url }}" class="img-responsive">
                        </a>
                        <div class="caption">
                            <h4>{{ professor.designation }}</h4>
                            <h5>{{ professor.Department }}</h5>

                            <!-- Update Profile -->
                            <a href="{% url 'IITG:prof_update' professor.pk %}" class="btn btn-primary btn-sm" role="button">Edit Profile</a>

                        </div>
                    </div>
                </div>

        <!-- Right cou</e Info -->
        <div class="col-sm-8 col-md-9">

            <ul class="nav nav-pills" style="margin-bottom: 10px;">
            </ul>

            <div class="panel panel-default">
                <div class="panel-body">
                    <!-- View Courses -->
                    <a href="{% url 'IITG:course_detail' professor.id %}" class="btn btn-primary btn-sm" role="button">Teaching</a>
                </div>
            </div>
            <div class="panel panel-default">
                <div class="panel-body">
                    <!-- View Education -->
                    <a href="{% url 'IITG:education_detail' professor.id %}" class="btn btn-primary btn-sm" role="button">Education</a>
                </div>
            </div>
            <div class="panel panel-default">
                <div class="panel-body">
                    <!-- View Professional Experience -->
                    <a href="{% url 'IITG:experience_detail' professor.id %}" class="btn btn-primary btn-sm" role="button">Professional Experience</a>
                </div>
            </div>
            <div class="panel panel-default">
                <div class="panel-body">
                    <!-- View Projects -->
                    <a href="{% url 'IITG:project_detail' professor.id %}" class="btn btn-primary btn-sm" role="button">Projects</a>
                </div>
            </div>
            <div class="panel panel-default">
                <div class="panel-body">
                    <!-- View Publication -->
                    <a href="{% url 'IITG:publication_detail' professor.id %}" class="btn btn-primary btn-sm" role="button">Publications</a>
                </div>
            </div>
            <div class="panel panel-default">
                <div class="panel-body">
                    <!-- View Recognition -->
                    <a href="{% url 'IITG:recognition_detail' professor.id %}" class="btn btn-primary btn-sm" role="button">Recognition</a>
                </div>
            </div>
            <div class="panel panel-default">
                <div class="panel-body">
                    <!-- View Student -->
                    <a href="{% url 'IITG:student_detail' professor.id %}" class="btn btn-primary btn-sm" role="button">Student</a>
                </div>
            </div>

                {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
            {% endfor %}
        {% else %}
            <div class="col-sm-12">
                <br>
                <a href="{% url 'IITG:create_professor' %}">
                    <button type="button" class="btn btn-success">
                        <span class="glyphicon glyphicon-plus"></span>&nbsp; Add details
                    </button>
                </a>
            </div>
        {% endif %}
    </div>

    <!-- If user searches and there are courses -->
    {% if courses %}
        <div class="row">
            <div class="col-sm-12">
                <h3>courses</h3>
            </div>
            <div class="col-sm-12">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Course Name</th>
                                    <th>Professor</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for course in courses %}
                                    <tr>
                                        <td>{{ course.name }}</td>
                                        <td>{{ course.professor.user }}</td>
                                        <td>
                                            <a href="{% url 'IITG:course_detail' course.professor.id %}">
                                                <img src="{{ course.professor.pro_pic.url }}" class="img-responsive" style="width: 20px; float: left; margin-right: 10px;" />
                                            </a>
                                            <a href="{% url 'IITG:course_detail' course.professor.id %}">{{ course.professor.user }}</a>
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}

</div>
{% endblock %}

sslp/IITG/templates/IITG/prof_detail.html
{% extends 'IITG/base.html' %}
{% block title %}IITG: {{ professor.user }}{% endblock %}
{% block professors_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">

        <!-- Left professor Info -->
        <div class="col-sm-4 col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">
                        <a href="{% url 'IITG:prof_detail' professor.id %}">
                            {% if professor.pro_pic %}
                                <img src="{{ professor.pro_pic.url }}" class="img-responsive">
                            {% else %}
                                <h3>No image to display</h3>
                            {% endif %}
                        </a>
                    <h2>{{ professor.user }} </h2>
                    <h2><small>{{ professor.designation }}</small></h2>
                    <h3>{{ professor.Department }}</h3>
                    <br>
                    <h4><small>Phone no. {{ professor.phone_no }}</small></h4>
                    <h4><small>Room no. {{ professor.room_no }}</small></h4>
                </div>
            </div>
        </div>

        <!-- Right course Info -->
        <div class="col-sm-8 col-md-9">

            <ul class="nav nav-pills" style="margin-bottom: 10px;">
            </ul>

            <div class="panel panel-default">
                <div class="panel-body">
                    <h3><u>Education</u></h3>
                        <br>
                        {% for education in professor.education_set.all %}
                           <li>{{ education.degree }} in {{ education.field }} from {{ education.University }},{{ education.Year }}</li>
                        {% endfor %}
                </div>
            </div>
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3><u>Research Interests</u></h3>
                        <br>
                        {{ professor.Research_Interests }}
                </div>
            </div>
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3><u>Biography</u></h3>
                        <br>
                        {{ professor.Biography }}
                </div>
            </div>
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3><u>Professional Experience</u></h3>
                        <br>
                        {% for experience in professor.experience_set.all %}
                           <li>{{ experience.Detail }}, {{ experience.Institution }}, {{ experience.start_Year }}-{{ experience.end_Year }}</li>
                        {% endfor %}
                </div>
            </div>
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3><u>Projects</u></h3>
                        <br>
                        {% for project in professor.projects_set.all %}
                    <li><b>{{ project.Title }}</b>, {{ project.Detail }}, {{ project.start_Year }}-{{ project.end_Year }}</li>
                        {% endfor %}
                </div>
            </div>
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3><u>Publications</u></h3>
                        <br>
                        {% for publication in professor.publication_set.all %}
                    <li><b>{{ publication.Name }}</b>, {{ publication.Detail }}, {{ publication.Date }}</li>
                        {% endfor %}
                </div>
            </div>
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3><u>Teachings</u></h3>
                        <br>
                        {% for course in professor.course_set.all %}
                            <li>{{ course.name }}({{ course.no }})</li>
                        {% endfor %}
                </div>
            </div>
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3><u>Recognitions</u></h3>
                        <br>
                        {% for recognition in professor.recognition_set.all %}
                    <li><b>{{ recognition.Name }}</b>, {{ recognition.Detail }}</li>
                        {% endfor %}
                </div>
            </div>
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3><u>Student</u></h3>
                        <br>
                        {% for student in professor.student_set.all %}
                        <li><b>{{ student.Name }}, {{ student.degree }} Student</b><br>
                            {{ student.Detail }}</li>
                        {% endfor %}
                </div>
            </div>
        </div>

    </div>

</div>

{% endblock %}

sslp/IITG/templates/IITG/project_detail.html
{% extends 'IITG/base.html' %}
{% block title %}IITG: {{ professor }}{% endblock %}
{% block professors_active %}active{% endblock %}

{% block body %}
<div class="container-fluid projects-container">

    <div class="row">

        <!-- Left professor Info -->
        <div class="col-sm-4 col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">
                    <a href="{% url 'IITG:project_detail' professor.id %}">
                        {% if professor.pro_pic %}
                            <img src="{{ professor.pro_pic.url }}" class="img-responsive">
                        {% else %}
                            <h3>No image to display</h3>
                        {% endif %}
                    </a>
                    <h1>{{ professor.user }} </h1>
                    <h1><small>{{ professor.designation }}</small></h1>
                    <h2>{{ professor.Department }}</h2>
                </div>
            </div>
        </div>

        <!-- Right project Info -->
        <div class="col-sm-8 col-md-9">

            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation" class="active"><a href="{% url 'IITG:project_detail' professor.id %}">View All</a></li>
                <li role="presentation"><a href="{% url 'IITG:create_project' professor.id %}">Add a new Project</a></li>
            </ul>

            <div class="panel panel-default">
                <div class="panel-body">

                    <h3>All Projects</h3>

                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}

                    <table class="table">
                        <thead>
                        <tr>
                            <th>Project Title</th>
                            <th>Details</th>
                            <th>Year</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for project in professor.projects_set.all %}
                            <tr>
                                <td>{{ project.Title }}</td>
                                <td>{{ project.Detail }}</td>
                                <td>{{ project.start_Year }}-{{ project.end_Year }}</td>
                                <td>
                                    <form action="{% url 'IITG:delete_project' professor.id project.id %}" method="post" style="display: inline;">
                                        {% csrf_token %}
                                        <input type="hidden" name="project_id" value="{{ project.id }}" />
                                        <button type="submit" class="btn btn-danger btn-xs">
                                            <span class="glyphicon glyphicon-remove"></span>&nbsp; Delete
                                        </button>
                                    </form>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>

                </div>
            </div>

        </div>

    </div>

</div>

{% endblock %}

sslp/IITG/templates/IITG/publication_detail.html
{% extends 'IITG/base.html' %}
{% block title %}IITG: {{ professor }}{% endblock %}
{% block professors_active %}active{% endblock %}

{% block body %}
<div class="container-fluid publications-container">

    <div class="row">

        <!-- Left professor Info -->
        <div class="col-sm-4 col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">
                    <a href="{% url 'IITG:publication_detail' professor.id %}">
                        {% if professor.pro_pic %}
                            <img src="{{ professor.pro_pic.url }}" class="img-responsive">
                        {% else %}
                            <h3>No image to display</h3>
                        {% endif %}
                    </a>
                    <h1>{{ professor.user }} </h1>
                    <h1><small>{{ professor.designation }}</small></h1>
                    <h2>{{ professor.Department }}</h2>
                </div>
            </div>
        </div>

        <!-- Right publication Info -->
        <div class="col-sm-8 col-md-9">

            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation" class="active"><a href="{% url 'IITG:publication_detail' professor.id %}">View All</a></li>
                <li role="presentation"><a href="{% url 'IITG:create_publication' professor.id %}">Add a new Publication</a></li>
            </ul>

            <div class="panel panel-default">
                <div class="panel-body">

                    <h3>All Publications</h3>

                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}

                    <table class="table">
                        <thead>
                        <tr>
                            <th>Publication Name</th>
                            <th>Detail</th>
                            <th>Date</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for publication in professor.publication_set.all %}
                            <tr>
                                <td>{{ publication.Name }}</td>
                                <td>{{ publication.Detail }}</td>
                                <td>{{ publication.Date}}</td>
                                <td>
                                    <form action="{% url 'IITG:delete_publication' professor.id publication.id %}" method="post" style="display: inline;">
                                        {% csrf_token %}
                                        <input type="hidden" name="publication_id" value="{{ publication.id }}" />
                                        <button type="submit" class="btn btn-danger btn-xs">
                                            <span class="glyphicon glyphicon-remove"></span>&nbsp; Delete
                                        </button>
                                    </form>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>

                </div>
            </div>

        </div>

    </div>

</div>

{% endblock %}